sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --configuration=phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
